repos:
-   repo: https://github.com/dnephin/pre-commit-golang
    rev: v0.5.0
    hooks:
    -   id: go-fmt
    -   id: go-imports
    -   id: golangci-lint
    -   id: go-unit-tests
    -   id: go-vet
-   repo: https://github.com/Bahjat/pre-commit-golang
    rev: v1.0.2
    hooks:
    - id: go-static-check # install https://staticcheck.io/docs/