version: '3'
services:
  admins-backend:
    image: golang:1.21.3-alpine
    working_dir: /app
    volumes:
      - .:/app
    command: ["go", "run", "controller/main.go"]
    ports:
      - "8080:8080"
    environment:
      DB_URI: mongodb+srv://admin:admin123@taller-admins.ez0xrnf.mongodb.net/?retryWrites=true&w=majority
      UPTRACE_DSN: https://SAe6OtAs8ysrYmkJmM8t-Q@api.uptrace.dev?grpc=4317
