info:
  contact: {}
paths:
  /admin/helloworld:
    get:
      consumes:
      - application/json
      description: do ping
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: ping example
      tags:
      - example
  /admin/numbers:
    get:
      consumes:
      - application/json
      description: gets a list of numbers
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: list
      summary: Test function for getting a list of numbers
      tags:
      - example
    post:
      consumes:
      - application/json
      description: saves a number on a list
      parameters:
      - description: Number to be saved
        format: int
        in: query
        name: number
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: Test function for saving a number
      tags:
      - example
swagger: "2.0"
