# Chattie:
name: Go Fomat Check

on: [push, pull_request]

jobs:
  go-format-check:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.21

    - name: Run gofmt
      run: gofmt -s -l . | read && echo "Go code is not formatted properly" && exit 1 || exit 0
