name: GoLint And Static Check

on: [push, pull_request]

jobs:
  go-lint-check:
    name: "Run Go Lint Check"
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.21

    - name: Install golangci-lint
      run: go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest

    - name: Run golangci-lint
      run: golangci-lint run

  staticcheck:
    name: "Run Static Check"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.21

      - name: Install bahjat/pre-commit-golang
        run: go install github.com/Bahjat/pre-commit-golang@latest

      - name: Run Static Check
        run: pre-commit-golang run go-static-check
