name: Go Unit Tests

on: [push, pull_request]

jobs:
  go-unit-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.21
    - name: Get temporary mongo db running
      run: docker run -d -p 27017:27017 mongo

    - name: export DB_URI
      run: export DB_URI=mongodb://localhost:27017

    - name: Run Go unit tests
      run: go test ./...
